 steps:
  #make .env
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    # - |
    #   echo "MONGO_DB=${_MONGO_DB}" > .env
    #   echo "DISCORD_WEBHOOK=${_DISCORD_WEBHOOK}" > .env
    #   echo "DISCORD_ROLE=$_DISCORD_ROLE}" > .env

  #Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sandbox-api'
      - '.'
  # Push container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sandbox-api'

  # Deploy container image to Cloud Run sandbox-api
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'sandbox-api',
        '--image',
        'gcr.io/$PROJECT_ID/sandbox-api',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]